<a href="https://colab.research.google.com/github/abhiraj-mengade/Pytorch/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
t1 = torch.tensor(4.)
print(t1)
print(t1.dtype)
print(t1.shape)

tensor(4.)
torch.float32
torch.Size([])


In [6]:
t2 = torch.tensor([[[1,2],[2,3]],[[4,5],[6,7]]])
print(t2.shape)

torch.Size([2, 2, 2])


In [8]:
x = torch.tensor(2.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

y = w*x + b
y

tensor(13., grad_fn=<AddBackward0>)

In [9]:
y.backward()

In [10]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(2.)
dy/db: tensor(1.)


In [12]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = torch.from_numpy(x)
print(y)
z = y.numpy()
print(z)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


**Linear Regression:**

In [22]:
#inputs (temp, rainfall, humidity)
inputs = np.array([[74, 68, 47],
                   [92, 87, 68],
                   [102, 45, 34],
                   [68, 98, 72]], dtype = 'float32')
inputs = torch.from_numpy(inputs)

In [32]:
#targets (fruit1 yeild, fruit2 yeild)
targets = np.array([[58, 72],
                    [82, 101],
                    [119, 132],
                    [22, 38]], dtype='float32')
targets = torch.from_numpy(targets)

In [15]:
w = torch.randn(2,3 ,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.8291,  0.9716, -1.1362],
        [ 1.2409, -0.9020,  0.4677]], requires_grad=True)
tensor([ 1.6450, -1.6510], requires_grad=True)


In [26]:
def model(x):
  return x @ w.t() + b

In [37]:
preds = model(inputs)
print(preds)

tensor([[-29.4708,  54.2202],
        [-44.6740,  70.2333],
        [-59.9292, 103.6778],
        [-20.1552,  32.1178]], grad_fn=<AddBackward0>)


In [33]:
#Loss function
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff * diff) / diff.numel()

In [38]:
loss = mse(preds, targets)
print(loss)

tensor(7448.7056, grad_fn=<DivBackward0>)


In [35]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11474.5449,  -8800.3291,  -6586.4482],
        [ -2180.1941,  -1726.7742,  -1296.3127]])
tensor([-128.6425,  -24.5220])


In [36]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [57]:
#epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [58]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(52.1404, grad_fn=<DivBackward0>)


In [59]:
print(targets)
print(preds)

tensor([[ 58.,  72.],
        [ 82., 101.],
        [119., 132.],
        [ 22.,  38.]])
tensor([[ 65.7034,  72.4173],
        [ 68.1321,  92.4418],
        [121.7249, 135.4844],
        [ 28.1578,  43.8788]], grad_fn=<AddBackward0>)
